# Generated by Django 3.0.7 on 2020-06-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbill_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
