# Generated by Django 3.0.7 on 2020-06-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbill_api', '0002_ingredient_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='Ingredients',
        ),
    ]
